<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCRVmYSq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCRVmYSq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCRVmYSq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCRVmYSq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCRVmYSq\App_KernelDevDebugContainer([
    'container.build_hash' => 'CRVmYSq',
    'container.build_id' => '527db135',
    'container.build_time' => 1679567386,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCRVmYSq');
