<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBmXU2RO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBmXU2RO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBmXU2RO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBmXU2RO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBmXU2RO\App_KernelDevDebugContainer([
    'container.build_hash' => 'BmXU2RO',
    'container.build_id' => '87a6ed78',
    'container.build_time' => 1680198933,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBmXU2RO');
