<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIJywMhQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIJywMhQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIJywMhQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIJywMhQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIJywMhQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'IJywMhQ',
    'container.build_id' => '7db3f30f',
    'container.build_time' => 1680892532,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIJywMhQ');
